package com.example.myBatisGenerator;

import java.util.Arrays;
import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Host
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.User
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Select_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String selectPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Insert_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String insertPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Update_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String updatePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Delete_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String deletePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String createPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Drop_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String dropPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Reload_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String reloadPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Shutdown_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String shutdownPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Process_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String processPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.File_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String filePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Grant_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String grantPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.References_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String referencesPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Index_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String indexPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Alter_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String alterPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Show_db_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String showDbPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Super_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String superPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_tmp_table_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String createTmpTablePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Lock_tables_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String lockTablesPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Execute_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String executePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Repl_slave_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String replSlavePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Repl_client_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String replClientPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_view_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String createViewPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Show_view_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String showViewPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_routine_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String createRoutinePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Alter_routine_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String alterRoutinePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_user_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String createUserPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Event_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String eventPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Trigger_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String triggerPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_tablespace_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String createTablespacePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ssl_type
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String sslType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.max_questions
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private Integer maxQuestions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.max_updates
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private Integer maxUpdates;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.max_connections
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private Integer maxConnections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.max_user_connections
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private Integer maxUserConnections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.plugin
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String plugin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password_expired
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String passwordExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password_last_changed
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private Date passwordLastChanged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password_lifetime
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private Short passwordLifetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account_locked
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String accountLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_role_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String createRolePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Drop_role_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String dropRolePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password_reuse_history
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private Short passwordReuseHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password_reuse_time
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private Short passwordReuseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password_require_current
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String passwordRequireCurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ssl_cipher
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private byte[] sslCipher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.x509_issuer
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private byte[] x509Issuer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.x509_subject
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private byte[] x509Subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.authentication_string
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String authenticationString;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.User_attributes
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    private String userAttributes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Host
     *
     * @return the value of user.Host
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Host
     *
     * @param host the value for user.Host
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.User
     *
     * @return the value of user.User
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.User
     *
     * @param user the value for user.User
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Select_priv
     *
     * @return the value of user.Select_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getSelectPriv() {
        return selectPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Select_priv
     *
     * @param selectPriv the value for user.Select_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setSelectPriv(String selectPriv) {
        this.selectPriv = selectPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Insert_priv
     *
     * @return the value of user.Insert_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getInsertPriv() {
        return insertPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Insert_priv
     *
     * @param insertPriv the value for user.Insert_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setInsertPriv(String insertPriv) {
        this.insertPriv = insertPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Update_priv
     *
     * @return the value of user.Update_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getUpdatePriv() {
        return updatePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Update_priv
     *
     * @param updatePriv the value for user.Update_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setUpdatePriv(String updatePriv) {
        this.updatePriv = updatePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Delete_priv
     *
     * @return the value of user.Delete_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getDeletePriv() {
        return deletePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Delete_priv
     *
     * @param deletePriv the value for user.Delete_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setDeletePriv(String deletePriv) {
        this.deletePriv = deletePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_priv
     *
     * @return the value of user.Create_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getCreatePriv() {
        return createPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_priv
     *
     * @param createPriv the value for user.Create_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setCreatePriv(String createPriv) {
        this.createPriv = createPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Drop_priv
     *
     * @return the value of user.Drop_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getDropPriv() {
        return dropPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Drop_priv
     *
     * @param dropPriv the value for user.Drop_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setDropPriv(String dropPriv) {
        this.dropPriv = dropPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Reload_priv
     *
     * @return the value of user.Reload_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getReloadPriv() {
        return reloadPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Reload_priv
     *
     * @param reloadPriv the value for user.Reload_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setReloadPriv(String reloadPriv) {
        this.reloadPriv = reloadPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Shutdown_priv
     *
     * @return the value of user.Shutdown_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getShutdownPriv() {
        return shutdownPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Shutdown_priv
     *
     * @param shutdownPriv the value for user.Shutdown_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setShutdownPriv(String shutdownPriv) {
        this.shutdownPriv = shutdownPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Process_priv
     *
     * @return the value of user.Process_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getProcessPriv() {
        return processPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Process_priv
     *
     * @param processPriv the value for user.Process_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setProcessPriv(String processPriv) {
        this.processPriv = processPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.File_priv
     *
     * @return the value of user.File_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getFilePriv() {
        return filePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.File_priv
     *
     * @param filePriv the value for user.File_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setFilePriv(String filePriv) {
        this.filePriv = filePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Grant_priv
     *
     * @return the value of user.Grant_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getGrantPriv() {
        return grantPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Grant_priv
     *
     * @param grantPriv the value for user.Grant_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setGrantPriv(String grantPriv) {
        this.grantPriv = grantPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.References_priv
     *
     * @return the value of user.References_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getReferencesPriv() {
        return referencesPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.References_priv
     *
     * @param referencesPriv the value for user.References_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setReferencesPriv(String referencesPriv) {
        this.referencesPriv = referencesPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Index_priv
     *
     * @return the value of user.Index_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getIndexPriv() {
        return indexPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Index_priv
     *
     * @param indexPriv the value for user.Index_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setIndexPriv(String indexPriv) {
        this.indexPriv = indexPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Alter_priv
     *
     * @return the value of user.Alter_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getAlterPriv() {
        return alterPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Alter_priv
     *
     * @param alterPriv the value for user.Alter_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setAlterPriv(String alterPriv) {
        this.alterPriv = alterPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Show_db_priv
     *
     * @return the value of user.Show_db_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getShowDbPriv() {
        return showDbPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Show_db_priv
     *
     * @param showDbPriv the value for user.Show_db_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setShowDbPriv(String showDbPriv) {
        this.showDbPriv = showDbPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Super_priv
     *
     * @return the value of user.Super_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getSuperPriv() {
        return superPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Super_priv
     *
     * @param superPriv the value for user.Super_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setSuperPriv(String superPriv) {
        this.superPriv = superPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_tmp_table_priv
     *
     * @return the value of user.Create_tmp_table_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getCreateTmpTablePriv() {
        return createTmpTablePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_tmp_table_priv
     *
     * @param createTmpTablePriv the value for user.Create_tmp_table_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setCreateTmpTablePriv(String createTmpTablePriv) {
        this.createTmpTablePriv = createTmpTablePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Lock_tables_priv
     *
     * @return the value of user.Lock_tables_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getLockTablesPriv() {
        return lockTablesPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Lock_tables_priv
     *
     * @param lockTablesPriv the value for user.Lock_tables_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setLockTablesPriv(String lockTablesPriv) {
        this.lockTablesPriv = lockTablesPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Execute_priv
     *
     * @return the value of user.Execute_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getExecutePriv() {
        return executePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Execute_priv
     *
     * @param executePriv the value for user.Execute_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setExecutePriv(String executePriv) {
        this.executePriv = executePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Repl_slave_priv
     *
     * @return the value of user.Repl_slave_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getReplSlavePriv() {
        return replSlavePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Repl_slave_priv
     *
     * @param replSlavePriv the value for user.Repl_slave_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setReplSlavePriv(String replSlavePriv) {
        this.replSlavePriv = replSlavePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Repl_client_priv
     *
     * @return the value of user.Repl_client_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getReplClientPriv() {
        return replClientPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Repl_client_priv
     *
     * @param replClientPriv the value for user.Repl_client_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setReplClientPriv(String replClientPriv) {
        this.replClientPriv = replClientPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_view_priv
     *
     * @return the value of user.Create_view_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getCreateViewPriv() {
        return createViewPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_view_priv
     *
     * @param createViewPriv the value for user.Create_view_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setCreateViewPriv(String createViewPriv) {
        this.createViewPriv = createViewPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Show_view_priv
     *
     * @return the value of user.Show_view_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getShowViewPriv() {
        return showViewPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Show_view_priv
     *
     * @param showViewPriv the value for user.Show_view_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setShowViewPriv(String showViewPriv) {
        this.showViewPriv = showViewPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_routine_priv
     *
     * @return the value of user.Create_routine_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getCreateRoutinePriv() {
        return createRoutinePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_routine_priv
     *
     * @param createRoutinePriv the value for user.Create_routine_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setCreateRoutinePriv(String createRoutinePriv) {
        this.createRoutinePriv = createRoutinePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Alter_routine_priv
     *
     * @return the value of user.Alter_routine_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getAlterRoutinePriv() {
        return alterRoutinePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Alter_routine_priv
     *
     * @param alterRoutinePriv the value for user.Alter_routine_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setAlterRoutinePriv(String alterRoutinePriv) {
        this.alterRoutinePriv = alterRoutinePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_user_priv
     *
     * @return the value of user.Create_user_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getCreateUserPriv() {
        return createUserPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_user_priv
     *
     * @param createUserPriv the value for user.Create_user_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setCreateUserPriv(String createUserPriv) {
        this.createUserPriv = createUserPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Event_priv
     *
     * @return the value of user.Event_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getEventPriv() {
        return eventPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Event_priv
     *
     * @param eventPriv the value for user.Event_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setEventPriv(String eventPriv) {
        this.eventPriv = eventPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Trigger_priv
     *
     * @return the value of user.Trigger_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getTriggerPriv() {
        return triggerPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Trigger_priv
     *
     * @param triggerPriv the value for user.Trigger_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setTriggerPriv(String triggerPriv) {
        this.triggerPriv = triggerPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_tablespace_priv
     *
     * @return the value of user.Create_tablespace_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getCreateTablespacePriv() {
        return createTablespacePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_tablespace_priv
     *
     * @param createTablespacePriv the value for user.Create_tablespace_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setCreateTablespacePriv(String createTablespacePriv) {
        this.createTablespacePriv = createTablespacePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ssl_type
     *
     * @return the value of user.ssl_type
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getSslType() {
        return sslType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ssl_type
     *
     * @param sslType the value for user.ssl_type
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setSslType(String sslType) {
        this.sslType = sslType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.max_questions
     *
     * @return the value of user.max_questions
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public Integer getMaxQuestions() {
        return maxQuestions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.max_questions
     *
     * @param maxQuestions the value for user.max_questions
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setMaxQuestions(Integer maxQuestions) {
        this.maxQuestions = maxQuestions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.max_updates
     *
     * @return the value of user.max_updates
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public Integer getMaxUpdates() {
        return maxUpdates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.max_updates
     *
     * @param maxUpdates the value for user.max_updates
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setMaxUpdates(Integer maxUpdates) {
        this.maxUpdates = maxUpdates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.max_connections
     *
     * @return the value of user.max_connections
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public Integer getMaxConnections() {
        return maxConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.max_connections
     *
     * @param maxConnections the value for user.max_connections
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setMaxConnections(Integer maxConnections) {
        this.maxConnections = maxConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.max_user_connections
     *
     * @return the value of user.max_user_connections
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public Integer getMaxUserConnections() {
        return maxUserConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.max_user_connections
     *
     * @param maxUserConnections the value for user.max_user_connections
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setMaxUserConnections(Integer maxUserConnections) {
        this.maxUserConnections = maxUserConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.plugin
     *
     * @return the value of user.plugin
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getPlugin() {
        return plugin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.plugin
     *
     * @param plugin the value for user.plugin
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setPlugin(String plugin) {
        this.plugin = plugin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password_expired
     *
     * @return the value of user.password_expired
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getPasswordExpired() {
        return passwordExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password_expired
     *
     * @param passwordExpired the value for user.password_expired
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setPasswordExpired(String passwordExpired) {
        this.passwordExpired = passwordExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password_last_changed
     *
     * @return the value of user.password_last_changed
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public Date getPasswordLastChanged() {
        return passwordLastChanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password_last_changed
     *
     * @param passwordLastChanged the value for user.password_last_changed
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setPasswordLastChanged(Date passwordLastChanged) {
        this.passwordLastChanged = passwordLastChanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password_lifetime
     *
     * @return the value of user.password_lifetime
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public Short getPasswordLifetime() {
        return passwordLifetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password_lifetime
     *
     * @param passwordLifetime the value for user.password_lifetime
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setPasswordLifetime(Short passwordLifetime) {
        this.passwordLifetime = passwordLifetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account_locked
     *
     * @return the value of user.account_locked
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getAccountLocked() {
        return accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account_locked
     *
     * @param accountLocked the value for user.account_locked
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setAccountLocked(String accountLocked) {
        this.accountLocked = accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_role_priv
     *
     * @return the value of user.Create_role_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getCreateRolePriv() {
        return createRolePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_role_priv
     *
     * @param createRolePriv the value for user.Create_role_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setCreateRolePriv(String createRolePriv) {
        this.createRolePriv = createRolePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Drop_role_priv
     *
     * @return the value of user.Drop_role_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getDropRolePriv() {
        return dropRolePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Drop_role_priv
     *
     * @param dropRolePriv the value for user.Drop_role_priv
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setDropRolePriv(String dropRolePriv) {
        this.dropRolePriv = dropRolePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password_reuse_history
     *
     * @return the value of user.Password_reuse_history
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public Short getPasswordReuseHistory() {
        return passwordReuseHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password_reuse_history
     *
     * @param passwordReuseHistory the value for user.Password_reuse_history
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setPasswordReuseHistory(Short passwordReuseHistory) {
        this.passwordReuseHistory = passwordReuseHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password_reuse_time
     *
     * @return the value of user.Password_reuse_time
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public Short getPasswordReuseTime() {
        return passwordReuseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password_reuse_time
     *
     * @param passwordReuseTime the value for user.Password_reuse_time
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setPasswordReuseTime(Short passwordReuseTime) {
        this.passwordReuseTime = passwordReuseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password_require_current
     *
     * @return the value of user.Password_require_current
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getPasswordRequireCurrent() {
        return passwordRequireCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password_require_current
     *
     * @param passwordRequireCurrent the value for user.Password_require_current
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setPasswordRequireCurrent(String passwordRequireCurrent) {
        this.passwordRequireCurrent = passwordRequireCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ssl_cipher
     *
     * @return the value of user.ssl_cipher
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public byte[] getSslCipher() {
        return sslCipher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ssl_cipher
     *
     * @param sslCipher the value for user.ssl_cipher
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setSslCipher(byte[] sslCipher) {
        this.sslCipher = sslCipher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.x509_issuer
     *
     * @return the value of user.x509_issuer
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public byte[] getX509Issuer() {
        return x509Issuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.x509_issuer
     *
     * @param x509Issuer the value for user.x509_issuer
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setX509Issuer(byte[] x509Issuer) {
        this.x509Issuer = x509Issuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.x509_subject
     *
     * @return the value of user.x509_subject
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public byte[] getX509Subject() {
        return x509Subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.x509_subject
     *
     * @param x509Subject the value for user.x509_subject
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setX509Subject(byte[] x509Subject) {
        this.x509Subject = x509Subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.authentication_string
     *
     * @return the value of user.authentication_string
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getAuthenticationString() {
        return authenticationString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.authentication_string
     *
     * @param authenticationString the value for user.authentication_string
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setAuthenticationString(String authenticationString) {
        this.authenticationString = authenticationString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.User_attributes
     *
     * @return the value of user.User_attributes
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public String getUserAttributes() {
        return userAttributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.User_attributes
     *
     * @param userAttributes the value for user.User_attributes
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    public void setUserAttributes(String userAttributes) {
        this.userAttributes = userAttributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", host=").append(host);
        sb.append(", user=").append(user);
        sb.append(", selectPriv=").append(selectPriv);
        sb.append(", insertPriv=").append(insertPriv);
        sb.append(", updatePriv=").append(updatePriv);
        sb.append(", deletePriv=").append(deletePriv);
        sb.append(", createPriv=").append(createPriv);
        sb.append(", dropPriv=").append(dropPriv);
        sb.append(", reloadPriv=").append(reloadPriv);
        sb.append(", shutdownPriv=").append(shutdownPriv);
        sb.append(", processPriv=").append(processPriv);
        sb.append(", filePriv=").append(filePriv);
        sb.append(", grantPriv=").append(grantPriv);
        sb.append(", referencesPriv=").append(referencesPriv);
        sb.append(", indexPriv=").append(indexPriv);
        sb.append(", alterPriv=").append(alterPriv);
        sb.append(", showDbPriv=").append(showDbPriv);
        sb.append(", superPriv=").append(superPriv);
        sb.append(", createTmpTablePriv=").append(createTmpTablePriv);
        sb.append(", lockTablesPriv=").append(lockTablesPriv);
        sb.append(", executePriv=").append(executePriv);
        sb.append(", replSlavePriv=").append(replSlavePriv);
        sb.append(", replClientPriv=").append(replClientPriv);
        sb.append(", createViewPriv=").append(createViewPriv);
        sb.append(", showViewPriv=").append(showViewPriv);
        sb.append(", createRoutinePriv=").append(createRoutinePriv);
        sb.append(", alterRoutinePriv=").append(alterRoutinePriv);
        sb.append(", createUserPriv=").append(createUserPriv);
        sb.append(", eventPriv=").append(eventPriv);
        sb.append(", triggerPriv=").append(triggerPriv);
        sb.append(", createTablespacePriv=").append(createTablespacePriv);
        sb.append(", sslType=").append(sslType);
        sb.append(", maxQuestions=").append(maxQuestions);
        sb.append(", maxUpdates=").append(maxUpdates);
        sb.append(", maxConnections=").append(maxConnections);
        sb.append(", maxUserConnections=").append(maxUserConnections);
        sb.append(", plugin=").append(plugin);
        sb.append(", passwordExpired=").append(passwordExpired);
        sb.append(", passwordLastChanged=").append(passwordLastChanged);
        sb.append(", passwordLifetime=").append(passwordLifetime);
        sb.append(", accountLocked=").append(accountLocked);
        sb.append(", createRolePriv=").append(createRolePriv);
        sb.append(", dropRolePriv=").append(dropRolePriv);
        sb.append(", passwordReuseHistory=").append(passwordReuseHistory);
        sb.append(", passwordReuseTime=").append(passwordReuseTime);
        sb.append(", passwordRequireCurrent=").append(passwordRequireCurrent);
        sb.append(", sslCipher=").append(sslCipher);
        sb.append(", x509Issuer=").append(x509Issuer);
        sb.append(", x509Subject=").append(x509Subject);
        sb.append(", authenticationString=").append(authenticationString);
        sb.append(", userAttributes=").append(userAttributes);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getHost() == null ? other.getHost() == null : this.getHost().equals(other.getHost()))
            && (this.getUser() == null ? other.getUser() == null : this.getUser().equals(other.getUser()))
            && (this.getSelectPriv() == null ? other.getSelectPriv() == null : this.getSelectPriv().equals(other.getSelectPriv()))
            && (this.getInsertPriv() == null ? other.getInsertPriv() == null : this.getInsertPriv().equals(other.getInsertPriv()))
            && (this.getUpdatePriv() == null ? other.getUpdatePriv() == null : this.getUpdatePriv().equals(other.getUpdatePriv()))
            && (this.getDeletePriv() == null ? other.getDeletePriv() == null : this.getDeletePriv().equals(other.getDeletePriv()))
            && (this.getCreatePriv() == null ? other.getCreatePriv() == null : this.getCreatePriv().equals(other.getCreatePriv()))
            && (this.getDropPriv() == null ? other.getDropPriv() == null : this.getDropPriv().equals(other.getDropPriv()))
            && (this.getReloadPriv() == null ? other.getReloadPriv() == null : this.getReloadPriv().equals(other.getReloadPriv()))
            && (this.getShutdownPriv() == null ? other.getShutdownPriv() == null : this.getShutdownPriv().equals(other.getShutdownPriv()))
            && (this.getProcessPriv() == null ? other.getProcessPriv() == null : this.getProcessPriv().equals(other.getProcessPriv()))
            && (this.getFilePriv() == null ? other.getFilePriv() == null : this.getFilePriv().equals(other.getFilePriv()))
            && (this.getGrantPriv() == null ? other.getGrantPriv() == null : this.getGrantPriv().equals(other.getGrantPriv()))
            && (this.getReferencesPriv() == null ? other.getReferencesPriv() == null : this.getReferencesPriv().equals(other.getReferencesPriv()))
            && (this.getIndexPriv() == null ? other.getIndexPriv() == null : this.getIndexPriv().equals(other.getIndexPriv()))
            && (this.getAlterPriv() == null ? other.getAlterPriv() == null : this.getAlterPriv().equals(other.getAlterPriv()))
            && (this.getShowDbPriv() == null ? other.getShowDbPriv() == null : this.getShowDbPriv().equals(other.getShowDbPriv()))
            && (this.getSuperPriv() == null ? other.getSuperPriv() == null : this.getSuperPriv().equals(other.getSuperPriv()))
            && (this.getCreateTmpTablePriv() == null ? other.getCreateTmpTablePriv() == null : this.getCreateTmpTablePriv().equals(other.getCreateTmpTablePriv()))
            && (this.getLockTablesPriv() == null ? other.getLockTablesPriv() == null : this.getLockTablesPriv().equals(other.getLockTablesPriv()))
            && (this.getExecutePriv() == null ? other.getExecutePriv() == null : this.getExecutePriv().equals(other.getExecutePriv()))
            && (this.getReplSlavePriv() == null ? other.getReplSlavePriv() == null : this.getReplSlavePriv().equals(other.getReplSlavePriv()))
            && (this.getReplClientPriv() == null ? other.getReplClientPriv() == null : this.getReplClientPriv().equals(other.getReplClientPriv()))
            && (this.getCreateViewPriv() == null ? other.getCreateViewPriv() == null : this.getCreateViewPriv().equals(other.getCreateViewPriv()))
            && (this.getShowViewPriv() == null ? other.getShowViewPriv() == null : this.getShowViewPriv().equals(other.getShowViewPriv()))
            && (this.getCreateRoutinePriv() == null ? other.getCreateRoutinePriv() == null : this.getCreateRoutinePriv().equals(other.getCreateRoutinePriv()))
            && (this.getAlterRoutinePriv() == null ? other.getAlterRoutinePriv() == null : this.getAlterRoutinePriv().equals(other.getAlterRoutinePriv()))
            && (this.getCreateUserPriv() == null ? other.getCreateUserPriv() == null : this.getCreateUserPriv().equals(other.getCreateUserPriv()))
            && (this.getEventPriv() == null ? other.getEventPriv() == null : this.getEventPriv().equals(other.getEventPriv()))
            && (this.getTriggerPriv() == null ? other.getTriggerPriv() == null : this.getTriggerPriv().equals(other.getTriggerPriv()))
            && (this.getCreateTablespacePriv() == null ? other.getCreateTablespacePriv() == null : this.getCreateTablespacePriv().equals(other.getCreateTablespacePriv()))
            && (this.getSslType() == null ? other.getSslType() == null : this.getSslType().equals(other.getSslType()))
            && (this.getMaxQuestions() == null ? other.getMaxQuestions() == null : this.getMaxQuestions().equals(other.getMaxQuestions()))
            && (this.getMaxUpdates() == null ? other.getMaxUpdates() == null : this.getMaxUpdates().equals(other.getMaxUpdates()))
            && (this.getMaxConnections() == null ? other.getMaxConnections() == null : this.getMaxConnections().equals(other.getMaxConnections()))
            && (this.getMaxUserConnections() == null ? other.getMaxUserConnections() == null : this.getMaxUserConnections().equals(other.getMaxUserConnections()))
            && (this.getPlugin() == null ? other.getPlugin() == null : this.getPlugin().equals(other.getPlugin()))
            && (this.getPasswordExpired() == null ? other.getPasswordExpired() == null : this.getPasswordExpired().equals(other.getPasswordExpired()))
            && (this.getPasswordLastChanged() == null ? other.getPasswordLastChanged() == null : this.getPasswordLastChanged().equals(other.getPasswordLastChanged()))
            && (this.getPasswordLifetime() == null ? other.getPasswordLifetime() == null : this.getPasswordLifetime().equals(other.getPasswordLifetime()))
            && (this.getAccountLocked() == null ? other.getAccountLocked() == null : this.getAccountLocked().equals(other.getAccountLocked()))
            && (this.getCreateRolePriv() == null ? other.getCreateRolePriv() == null : this.getCreateRolePriv().equals(other.getCreateRolePriv()))
            && (this.getDropRolePriv() == null ? other.getDropRolePriv() == null : this.getDropRolePriv().equals(other.getDropRolePriv()))
            && (this.getPasswordReuseHistory() == null ? other.getPasswordReuseHistory() == null : this.getPasswordReuseHistory().equals(other.getPasswordReuseHistory()))
            && (this.getPasswordReuseTime() == null ? other.getPasswordReuseTime() == null : this.getPasswordReuseTime().equals(other.getPasswordReuseTime()))
            && (this.getPasswordRequireCurrent() == null ? other.getPasswordRequireCurrent() == null : this.getPasswordRequireCurrent().equals(other.getPasswordRequireCurrent()))
            && (Arrays.equals(this.getSslCipher(), other.getSslCipher()))
            && (Arrays.equals(this.getX509Issuer(), other.getX509Issuer()))
            && (Arrays.equals(this.getX509Subject(), other.getX509Subject()))
            && (this.getAuthenticationString() == null ? other.getAuthenticationString() == null : this.getAuthenticationString().equals(other.getAuthenticationString()))
            && (this.getUserAttributes() == null ? other.getUserAttributes() == null : this.getUserAttributes().equals(other.getUserAttributes()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Apr 30 18:13:11 CST 2024
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getHost() == null) ? 0 : getHost().hashCode());
        result = prime * result + ((getUser() == null) ? 0 : getUser().hashCode());
        result = prime * result + ((getSelectPriv() == null) ? 0 : getSelectPriv().hashCode());
        result = prime * result + ((getInsertPriv() == null) ? 0 : getInsertPriv().hashCode());
        result = prime * result + ((getUpdatePriv() == null) ? 0 : getUpdatePriv().hashCode());
        result = prime * result + ((getDeletePriv() == null) ? 0 : getDeletePriv().hashCode());
        result = prime * result + ((getCreatePriv() == null) ? 0 : getCreatePriv().hashCode());
        result = prime * result + ((getDropPriv() == null) ? 0 : getDropPriv().hashCode());
        result = prime * result + ((getReloadPriv() == null) ? 0 : getReloadPriv().hashCode());
        result = prime * result + ((getShutdownPriv() == null) ? 0 : getShutdownPriv().hashCode());
        result = prime * result + ((getProcessPriv() == null) ? 0 : getProcessPriv().hashCode());
        result = prime * result + ((getFilePriv() == null) ? 0 : getFilePriv().hashCode());
        result = prime * result + ((getGrantPriv() == null) ? 0 : getGrantPriv().hashCode());
        result = prime * result + ((getReferencesPriv() == null) ? 0 : getReferencesPriv().hashCode());
        result = prime * result + ((getIndexPriv() == null) ? 0 : getIndexPriv().hashCode());
        result = prime * result + ((getAlterPriv() == null) ? 0 : getAlterPriv().hashCode());
        result = prime * result + ((getShowDbPriv() == null) ? 0 : getShowDbPriv().hashCode());
        result = prime * result + ((getSuperPriv() == null) ? 0 : getSuperPriv().hashCode());
        result = prime * result + ((getCreateTmpTablePriv() == null) ? 0 : getCreateTmpTablePriv().hashCode());
        result = prime * result + ((getLockTablesPriv() == null) ? 0 : getLockTablesPriv().hashCode());
        result = prime * result + ((getExecutePriv() == null) ? 0 : getExecutePriv().hashCode());
        result = prime * result + ((getReplSlavePriv() == null) ? 0 : getReplSlavePriv().hashCode());
        result = prime * result + ((getReplClientPriv() == null) ? 0 : getReplClientPriv().hashCode());
        result = prime * result + ((getCreateViewPriv() == null) ? 0 : getCreateViewPriv().hashCode());
        result = prime * result + ((getShowViewPriv() == null) ? 0 : getShowViewPriv().hashCode());
        result = prime * result + ((getCreateRoutinePriv() == null) ? 0 : getCreateRoutinePriv().hashCode());
        result = prime * result + ((getAlterRoutinePriv() == null) ? 0 : getAlterRoutinePriv().hashCode());
        result = prime * result + ((getCreateUserPriv() == null) ? 0 : getCreateUserPriv().hashCode());
        result = prime * result + ((getEventPriv() == null) ? 0 : getEventPriv().hashCode());
        result = prime * result + ((getTriggerPriv() == null) ? 0 : getTriggerPriv().hashCode());
        result = prime * result + ((getCreateTablespacePriv() == null) ? 0 : getCreateTablespacePriv().hashCode());
        result = prime * result + ((getSslType() == null) ? 0 : getSslType().hashCode());
        result = prime * result + ((getMaxQuestions() == null) ? 0 : getMaxQuestions().hashCode());
        result = prime * result + ((getMaxUpdates() == null) ? 0 : getMaxUpdates().hashCode());
        result = prime * result + ((getMaxConnections() == null) ? 0 : getMaxConnections().hashCode());
        result = prime * result + ((getMaxUserConnections() == null) ? 0 : getMaxUserConnections().hashCode());
        result = prime * result + ((getPlugin() == null) ? 0 : getPlugin().hashCode());
        result = prime * result + ((getPasswordExpired() == null) ? 0 : getPasswordExpired().hashCode());
        result = prime * result + ((getPasswordLastChanged() == null) ? 0 : getPasswordLastChanged().hashCode());
        result = prime * result + ((getPasswordLifetime() == null) ? 0 : getPasswordLifetime().hashCode());
        result = prime * result + ((getAccountLocked() == null) ? 0 : getAccountLocked().hashCode());
        result = prime * result + ((getCreateRolePriv() == null) ? 0 : getCreateRolePriv().hashCode());
        result = prime * result + ((getDropRolePriv() == null) ? 0 : getDropRolePriv().hashCode());
        result = prime * result + ((getPasswordReuseHistory() == null) ? 0 : getPasswordReuseHistory().hashCode());
        result = prime * result + ((getPasswordReuseTime() == null) ? 0 : getPasswordReuseTime().hashCode());
        result = prime * result + ((getPasswordRequireCurrent() == null) ? 0 : getPasswordRequireCurrent().hashCode());
        result = prime * result + (Arrays.hashCode(getSslCipher()));
        result = prime * result + (Arrays.hashCode(getX509Issuer()));
        result = prime * result + (Arrays.hashCode(getX509Subject()));
        result = prime * result + ((getAuthenticationString() == null) ? 0 : getAuthenticationString().hashCode());
        result = prime * result + ((getUserAttributes() == null) ? 0 : getUserAttributes().hashCode());
        return result;
    }
}